### ISSUE TITLE
cant access fedora boot

### ISSUE THREAD

**Issue by rfwn** [shvchk/poly-dark#14] opened 2022-05-10 15:28 UTC
Installed this theme from Fedora 36 (i dual booted it with windows) and it boot menu, for a little moment it says something like error (its too fast to read it) and shows the theme, but only with windows option, cant access fedora. how can i fix it (or just remove the theme). im new to linux so plz help me with clear instructions.

**Comment by shvchk** [comment] 2022-05-13 05:15
It's unlikely to be caused by the theme, I've just tested it on Fedora 36 VM (both UEFI and BIOS) and had no issues. Maybe try to record this error on camera, so it can then be paused to read the text.

If you want to disable the theme, just comment out (i.e. prepend with `#`) line starting with `GRUB_THEME=` in `/etc/default/grub`, then `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`, then reboot.

**Comment by rfwn** [comment] 2022-05-22 11:57
> It's unlikely to be caused by the theme, I've just tested it on Fedora 36 VM (both UEFI and BIOS) and had no issues. Maybe try to record this error on camera, so it can then be paused to read the text.

the error just appeared for the first time, and i dont it see it anymore

> If you want to disable the theme, just comment out (i.e. prepend with #) line starting with GRUB_THEME= in /etc/default/grub, then sudo grub2-mkconfig -o /boot/grub2/grub.cfg, then reboot.

i disabled the theme, but still cant see fedora in the boot menu.

**Comment by shvchk** [comment] 2023-07-24 03:35
The error might be related to shvchk/fallout-grub-theme#30 , in which case it is cosmetic and can be safely ignored.

I checked again in a VM, and it works fine. Closing for now, feel free to reopen if the issue still remains.

**Closed by shvchk** 2023-07-24 03:35 UTC
